plugin:
  name: easydb-example-plugin
  version: 1.0
  url: https://github.com/programmfabrik/easydb-example-plugin
  displayname:
    de-DE: Example Plugin
    en-US: Example Plugin
  info:
    de-DE: "Das Beispiel Plugin für **easydb**."
    en-US: "An example plugin for **easydb**."
  webhooks:
    - name: example
      secret_base_config: "example_plugin.webhook_secret"
  webfrontend:
    url: example-plugin.js
    l10n: l10n/
    css: example-plugin.css
    type_extension:
      mask:
        text_oneline:
          - name: "ex_text_online"
            parameters:
              ex_1:
                type: "text"
        eas:
          - name: ex_eas
            parameters:
              show:
                type: bool
                default: true

custom_events:
  - EASYDB_EXAMPLE_PLUGIN_EVENT

custom_types:
  slider:
    config:
      schema:
        - name: range
          parameters:
            from:
              type: int
              position: 0
            to:
              type: int
              position: 1
      mask:
        - name: appearance
          parameters:
            color:
              type: select
              options: ["red", "blue", "green"]
  example:
    update:
      script: build/update/example-update.js
      timeout: 10
      batch_size: 1000
      interval_base_config: default_update_interval.days

base_config:
  - name: example_plugin
    group: example
    parameters:
      text:
        type: text
        position: 0
      int:
        type: int
        position: 1
      email:
        type: email
        position: 2
      text_multi:
        type: text-multiline
        position: 3
      text_l10n:
        type: text-l10n
        position: 4
      text_l10n_multi:
        type: text-l10n-multiline
        position: 5
      string_list:
        type: string-list
        choices:
          - one
          - two
          - three
        position: 6
      string_list_sort:
        type: string-list-sort
        choice_label: "list-sort.choice"
        choices:
          - one
          - two
          - three
        position: 7
      select:
        type: select
        options:
          - apple
          - banana
          - kiwi
        position: 8
      date:
        type: text
        plugin_type: date
        position: 9
      tag_select:
        type: tag-select
        position: 10
      tagfilter_select:
        type: tagfilter-select
        position: 11
      profile_mapping:
        type: int
        plugin_type: profile_mapping_select
        position: 12
      easydb_group:
        type: int
        plugin_type: group_easydb_select
        position: 13
      bool:
        type: bool
        position: 14
      example_base_config:
        type: text
        plugin_type: example-base-config
        store_as_json: true
        position: 15
      webhook_secret:
        type: text
        default: ""
        position: 16

python-2:
  file: src/server/example.py

system_rights:
  - name: example
    comment: this right was added by a the example plugin
